const eventTypes = [
  {id:'attack',icon:'↗',name:'Ataque perigoso',desc:'Entrada no último terço',group:'Ofensivos'},
  {id:'shot',icon:'◎',name:'Remate',desc:'Tentativa de finalização',group:'Ofensivos'},
  {id:'target',icon:'◉',name:'Remate enquadrado',desc:'À baliza',group:'Ofensivos'},
  {id:'cross',icon:'⤴',name:'Cruzamento',desc:'Bola enviada para a área',group:'Ofensivos'},
  {id:'corner',icon:'⚑',name:'Canto',desc:'Bola parada ofensiva',group:'Ofensivos'},
  {id:'goal',icon:'●',name:'Golo',desc:'Golo do adversário',type:'danger',group:'Ofensivos'},
  {id:'tackle',icon:'◇',name:'Desarme',desc:'Retirada da bola ao adversário',group:'Defensivos'},
  {id:'interception',icon:'↯',name:'Interceção',desc:'Corte de uma linha de passe',group:'Defensivos'},
  {id:'clearance',icon:'↗',name:'Corte / alívio',desc:'Afastamento de uma situação de perigo',group:'Defensivos'},
  {id:'defensiveDuel',icon:'⚔',name:'Duelo defensivo ganho',desc:'Duelo individual vencido',group:'Defensivos'},
  {id:'shotBlock',icon:'▣',name:'Bloqueio de remate',desc:'Remate intercetado por um defensor',group:'Defensivos'},
  {id:'goalkeeperSave',icon:'✋',name:'Defesa do GR',desc:'Intervenção do guarda-redes',group:'Defensivos'},
  {id:'recover',icon:'↥',name:'Recuperação alta',desc:'No meio-campo ofensivo',group:'Transições'},
  {id:'loss',icon:'↧',name:'Perda perigosa',desc:'Em zona de risco',type:'danger',group:'Transições'},
  {id:'transition',icon:'⇄',name:'Transição rápida',desc:'Ataque após recuperação',group:'Transições'},
  {id:'foul',icon:'!',name:'Falta',desc:'Interrupção cometida',type:'warning',group:'Controlo'},
  {id:'offside',icon:'⚐',name:'Fora de jogo',desc:'Linha defensiva',group:'Controlo'},
  {id:'yellowCard',icon:'▮',name:'Cartão amarelo',desc:'Advertência disciplinar',type:'card-yellow',group:'Controlo'},
  {id:'secondYellow',icon:'▮▮',name:'Segundo amarelo',desc:'Expulsão por acumulação',type:'card-yellow',group:'Controlo'},
  {id:'redCard',icon:'▮',name:'Cartão vermelho',desc:'Expulsão direta',type:'card-red',group:'Controlo'}
];
const noteTypes=[
  {group:'Organização ofensiva',label:'Primeira fase de construção'},{group:'Organização ofensiva',label:'Progressão e corredor preferencial'},{group:'Organização ofensiva',label:'Criação e movimentos entre linhas'},{group:'Organização ofensiva',label:'Finalização e presença na área'},
  {group:'Organização defensiva',label:'Estrutura, bloco e distâncias'},{group:'Organização defensiva',label:'Gatilhos e orientação da pressão'},{group:'Organização defensiva',label:'Coberturas e proteção central'},{group:'Organização defensiva',label:'Profundidade e defesa de cruzamentos'},
  {group:'Transições',label:'Transição ofensiva após recuperação'},{group:'Transições',label:'Transição defensiva após perda'},
  {group:'Bolas paradas',label:'Bolas paradas ofensivas'},{group:'Bolas paradas',label:'Bolas paradas defensivas'}
];
const observationZones=[['left-attack','Esquerda · Ataque'],['center-attack','Centro · Ataque'],['right-attack','Direita · Ataque'],['left-mid','Esquerda · Meio-campo'],['center-mid','Centro · Meio-campo'],['right-mid','Direita · Meio-campo'],['left-defense','Esquerda · Defesa'],['center-defense','Centro · Defesa'],['right-defense','Direita · Defesa']];
const blank=()=>({scope:'opponent',team:'Adversário',score:0,seconds:0,running:false,period:'1.ª parte',events:[],notes:{},players:[],vulnerabilities:'',selectedZone:'center-mid',attackDirection:'right',competition:'',matchDate:'',venue:'',analyst:'',formation:'',opponentFormation:'',matchRound:'',homeAway:'',observationGoal:'',finalScore:'',systemChanges:'',substitutions:'',eventMoment:'Organização ofensiva',eventOutcome:'Neutro',eventRelation:'',matchState:'Empatado',eventPlayer:'',eventQuickNote:'',blockHeight:'',pressingStyle:'',buildUpStyle:'',attackTempo:'',strengths:'',weaknesses:'',howToCondition:'',howToExploit:'',trainingRecommendations:'',analysisPriority:''});
let state={...blank(),...JSON.parse(localStorage.getItem('rf-football-match')||'{}'),running:false};
let reports=JSON.parse(localStorage.getItem('rf-football-reports')||'[]'),activeReportId=null;
let timer,pendingCardType=null;
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
function save(){const updatedAt=Date.now();localStorage.setItem('rf-football-match',JSON.stringify(state));localStorage.setItem('rf-football-match-updated',String(updatedAt));window.dispatchEvent(new CustomEvent('rf:match-changed',{detail:{data:state,updatedAt}}));$('#savedText').textContent='Guardado agora';setTimeout(()=>$('#savedText').textContent='Guardado',900)}
function formatTime(s){return `${String(Math.floor(s/60)).padStart(2,'0')}:${String(s%60).padStart(2,'0')}`}
function toast(t){const el=$('#toast');el.textContent=t;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),1200)}
let deferredInstallPrompt=null;
const installAppBtn=$('#installAppBtn');
const isIos=/iphone|ipad|ipod/i.test(navigator.userAgent),isStandalone=matchMedia('(display-mode: standalone)').matches||navigator.standalone===true;
if(isIos&&!isStandalone){installAppBtn.hidden=false;installAppBtn.dataset.ios='true'}
window.addEventListener('beforeinstallprompt',event=>{event.preventDefault();deferredInstallPrompt=event;installAppBtn.hidden=false});
window.addEventListener('appinstalled',()=>{deferredInstallPrompt=null;installAppBtn.hidden=true;toast('RF Football instalada')});
installAppBtn.onclick=async()=>{if(installAppBtn.dataset.ios){alert('No iPhone: toque no botão Partilhar do Safari e escolha “Adicionar ao ecrã principal”.');return}if(!deferredInstallPrompt){toast('Abra a aplicação no Chrome ou Edge para instalar');return}deferredInstallPrompt.prompt();await deferredInstallPrompt.userChoice;deferredInstallPrompt=null;installAppBtn.hidden=true};
function persistReports(){const updatedAt=Date.now();localStorage.setItem('rf-football-reports',JSON.stringify(reports));localStorage.setItem('rf-football-reports-updated',String(updatedAt));window.dispatchEvent(new CustomEvent('rf:reports-changed',{detail:{data:reports,updatedAt}}));renderReportLibrary()}
function reportTitle(snapshot){const date=snapshot.matchDate?new Intl.DateTimeFormat('pt-PT').format(new Date(snapshot.matchDate+'T12:00:00')):new Intl.DateTimeFormat('pt-PT').format(new Date());return `${snapshot.team||'Equipa'} — ${date}`}
function renderReportLibrary(){const list=$('#reportList');if(!list)return;$('#reportCount').textContent=`${reports.length} ${reports.length===1?'relatório':'relatórios'}`;list.className=reports.length?'report-list':'empty';list.innerHTML=reports.length?reports.map(r=>`<article class="saved-report ${r.id===activeReportId?'active':''}"><div><h3>${escapeText(r.title)}</h3><p>${escapeText(r.competition||'Competição não definida')} · ${r.eventCount||0} acontecimentos · Atualizado ${new Intl.DateTimeFormat('pt-PT',{dateStyle:'short',timeStyle:'short'}).format(new Date(r.updatedAt))}</p></div><div class="saved-report-actions"><button data-open-report="${r.id}">Abrir e editar</button><button data-copy-report="${r.id}" title="Duplicar">⧉</button><button class="danger" data-delete-report="${r.id}" title="Eliminar">×</button></div></article>`).join(''):'Ainda não existem relatórios guardados.'}
function saveCurrentReport(){const now=Date.now(),snapshot=JSON.parse(JSON.stringify({...state,running:false}));let report=reports.find(r=>r.id===activeReportId);if(report){report.title=reportTitle(snapshot);report.competition=snapshot.competition;report.eventCount=snapshot.events.length;report.updatedAt=now;report.state=snapshot;toast('Relatório atualizado')}else{report={id:'report-'+now,title:reportTitle(snapshot),competition:snapshot.competition,eventCount:snapshot.events.length,createdAt:now,updatedAt:now,state:snapshot};reports.unshift(report);activeReportId=report.id;toast('Relatório guardado')}persistReports();renderReport()}
function openSavedReport(id){const report=reports.find(r=>r.id===id);if(!report)return;clearInterval(timer);activeReportId=id;state={...blank(),...JSON.parse(JSON.stringify(report.state)),running:false};sync();save();renderReport();renderReportLibrary();toast('Relatório aberto para edição')}
function renderEvents(){
  const counts=Object.fromEntries(eventTypes.map(e=>[e.id,state.events.filter(x=>x.id===e.id).length]));
  $('#eventGrid').innerHTML=['Ofensivos','Defensivos','Transições','Controlo'].map(group=>`<section class="event-group"><h3 class="event-group-title">${group}</h3><div class="event-group-grid">${eventTypes.filter(e=>e.group===group).map(e=>`<article class="event-card ${e.type||''}" title="${e.desc}"><span class="icon">${e.icon}</span><button data-event="${e.id}" aria-label="Adicionar ${e.name}">＋</button><h3>${e.name}</h3><p>${e.desc}</p><strong>${counts[e.id]}</strong></article>`).join('')}</div></section>`).join('');
  $('#eventCount').textContent=`${state.events.length} registados`; $('#undoBtn').disabled=!state.events.length;
  const typeFilter=$('#eventTypeFilter')?.value||'',periodFilter=$('#eventPeriodFilter')?.value||'';const filtered=state.events.map((event,index)=>({event,index})).filter(({event:x})=>(!typeFilter||x.id===typeFilter)&&(!periodFilter||x.period===periodFilter));
  $('#eventLog').className=filtered.length?'':'empty'; $('#eventLog').innerHTML=filtered.length?filtered.slice(-10).reverse().map(({event:x,index})=>{const type=eventTypes.find(e=>e.id===x.id),zone=observationZones.find(z=>z[0]===(x.zone||'center-mid'))?.[1]||'Zona não definida';return`<div class="log-row"><time>${formatTime(x.time)}</time><span>${type.icon}</span><b>${type.name}</b><span class="event-zone">${zone} · ${x.period||'1.ª parte'}${x.player?' · '+x.player:''}</span><button class="evidence-btn ${x.evidence?'active':''}" data-evidence="${index}" title="Marcar como evidência">★</button>${x.note?`<div class="event-note">${x.note}</div>`:''}</div>`}).join(''):'Nenhum evento corresponde aos filtros selecionados.';renderLastEvent();
}
function renderZones(){const ids=state.attackDirection==='right'?['left-defense','left-mid','left-attack','center-defense','center-mid','center-attack','right-defense','right-mid','right-attack']:['left-attack','left-mid','left-defense','center-attack','center-mid','center-defense','right-attack','right-mid','right-defense'];const zones=ids.map(id=>observationZones.find(z=>z[0]===id));$('#zoneGrid').innerHTML=zones.map(([id,name])=>{const total=state.events.filter(e=>(e.zone||'center-mid')===id).length;return`<button class="zone-cell ${state.selectedZone===id?'active':''}" data-zone="${id}">${name.split(' · ')[0]}<br>${name.split(' · ')[1]}${total?`<em>${total}</em>`:''}</button>`}).join('');$('#selectedZoneText').textContent=observationZones.find(z=>z[0]===state.selectedZone)?.[1]||'Centro · Meio-campo';$('#attackDirection').textContent=state.attackDirection==='right'?'Ataque →':'← Ataque'}
function renderQuickContext(){$('#quickContextSummary').textContent=`${state.eventMoment} · ${state.eventOutcome}`;$$('[data-outcome]').forEach(b=>b.classList.toggle('active',b.dataset.outcome===state.eventOutcome))}
function renderLastEvent(){const last=state.events.at(-1),has=!!last;$('#undoLastQuick').disabled=!has;$('#evidenceLastQuick').disabled=!has;$('#evidenceLastQuick').classList.toggle('active',!!last?.evidence);if(!last){$('#lastEventText').textContent='Nenhum evento registado';return}const type=eventTypes.find(e=>e.id===last.id),zone=observationZones.find(z=>z[0]===(last.zone||'center-mid'))?.[1];$('#lastEventText').textContent=`${formatTime(last.time)} · ${type?.name||last.id} · ${zone}`}
const cardEventIds=['yellowCard','secondYellow','redCard'];
function recordEvent(id,extra={}){state.events.push({id,time:state.seconds,zone:state.selectedZone,period:state.period,moment:state.eventMoment,outcome:state.eventOutcome,relation:state.eventRelation,matchState:state.matchState,player:state.eventPlayer,note:state.eventQuickNote,evidence:false,...extra});if(id==='goal')state.score++;state.eventQuickNote='';$('#eventQuickNote').value='';renderZones();renderEvents();renderNotes();$('#score').textContent=state.score;save();const zone=observationZones.find(z=>z[0]===state.selectedZone)?.[1];toast(`${eventTypes.find(x=>x.id===id).name} · ${formatTime(state.seconds)} · ${zone}`)}
function openCardDialog(type){pendingCardType=type;const titles={yellowCard:'Cartão amarelo',secondYellow:'Segundo amarelo e expulsão',redCard:'Cartão vermelho'};$('#cardDialogTitle').textContent=titles[type];$('#cardPlayer').innerHTML='<option value="">Sem identificação</option>'+state.players.map(p=>`<option value="${p.id}">${p.number?'#'+p.number+' — ':''}${p.name||p.position||'Jogador'}</option>`).join('');$('#cardPlayerManual').value='';$('#cardReason').value='';$('#cardNote').value='';$('#cardWarning').hidden=true;$('#cardDialog').showModal()}
function updateCardWarning(){const id=$('#cardPlayer').value,hasYellow=id&&state.events.some(e=>e.playerId===id&&e.id==='yellowCard');$('#cardWarning').hidden=!hasYellow}
const playerTagOptions=['Jogador-chave','Organizador','Ameaça na profundidade','Forte no 1x1','Vulnerável sob pressão','Agressivo defensivamente','Risco disciplinar'];
function playerDiscipline(player){const events=state.events.filter(e=>['yellowCard','secondYellow','redCard'].includes(e.id)&&(e.playerId===player.id||(!e.playerId&&e.player&&((player.name&&e.player.includes(player.name))||(player.number&&e.player.includes(player.number))))));return{yellow:events.filter(e=>e.id==='yellowCard').length,second:events.filter(e=>e.id==='secondYellow').length,red:events.filter(e=>e.id==='redCard').length}}
function renderNotes(){
  state.players.forEach(p=>p.id=p.id||newUid());
  let lastGroup='';$('#notesList').innerHTML=noteTypes.map((n,i)=>{const group=n.group!==lastGroup?`<div class="model-group-title">${n.group}</div>`:'';lastGroup=n.group;return`${group}<label class="note-card"><span>${n.label}</span><textarea data-note="${i}" placeholder="Comportamento, contexto, frequência e evidência…">${state.notes[i]||''}</textarea></label>`}).join('');
  $('#playersList').innerHTML=state.players.length?state.players.map((p,i)=>{const cards=playerDiscipline(p);return`<article class="player-card"><div class="player-card-head"><input data-player-number="${i}" inputmode="numeric" placeholder="#" value="${p.number||''}"><input data-player-position="${i}" placeholder="Posição" value="${p.position||''}"><input data-player-name="${i}" placeholder="Nome" value="${p.name||''}"><select data-player-rating="${i}" aria-label="Avaliação"><option value="">Nota</option>${[1,2,3,4,5,6,7,8,9,10].map(n=>`<option ${String(p.rating)===String(n)?'selected':''}>${n}</option>`).join('')}</select><button data-remove-player="${i}" aria-label="Remover">×</button></div>${cards.yellow||cards.second||cards.red?`<div class="discipline-badges">${cards.yellow?`<span class="discipline-badge yellow">${cards.yellow} amarelo${cards.yellow>1?'s':''}</span>`:''}${cards.second?`<span class="discipline-badge red">${cards.second} expulsão por 2.º amarelo</span>`:''}${cards.red?`<span class="discipline-badge red">${cards.red} vermelho${cards.red>1?'s':''}</span>`:''}</div>`:''}<div class="player-detail-grid"><input data-player-foot="${i}" placeholder="Pé dominante" value="${p.foot||''}"><input data-player-role="${i}" placeholder="Função no sistema" value="${p.role||''}"><textarea data-player-positive="${i}" placeholder="Ações e comportamentos positivos">${p.positive||''}</textarea><textarea data-player-improve="${i}" placeholder="Aspetos a explorar ou melhorar">${p.improve||''}</textarea></div><div class="player-tags">${playerTagOptions.map(tag=>`<button class="player-tag ${(p.tags||[]).includes(tag)?'active':''}" data-player-tag="${i}" data-tag="${tag}">${tag}</button>`).join('')}</div></article>`}).join(''):'<div class="empty">Adicione jogadores influentes ou vulneráveis.</div>';
  $('#vulnerabilities').value=state.vulnerabilities||'';
  ['blockHeight','pressingStyle','buildUpStyle','attackTempo'].forEach(id=>$('#'+id).value=state[id]||'');
  ['strengths','weaknesses','howToCondition','howToExploit','trainingRecommendations','analysisPriority'].forEach(id=>$('#'+id).value=state[id]||'');
  $('#eventPlayerList').innerHTML=state.players.map(p=>`<option value="${p.number?'#'+p.number+' ':''}${p.name||p.position||'Jogador'}">`).join('');
}
function count(id){return state.events.filter(e=>e.id===id).length}
function generateInsights(){
  const insights=[]; const shots=count('shot'), target=count('target'), attacks=count('attack');
  if(attacks>=6) insights.push(`Volume ofensivo elevado: ${attacks} ataques perigosos registados.`);
  if(shots) insights.push(`Eficácia de enquadramento de ${Math.round(target/shots*100)}% (${target} em ${shots} remates).`);
  if(count('recover')>=3) insights.push('Pressiona e recupera alto com frequência; preparar uma saída apoiada e uma solução longa.');
  if(count('transition')>=3) insights.push('A transição ofensiva é uma ameaça recorrente; proteger o corredor central após perda.');
  if(count('loss')>=3) insights.push('Comete perdas em zonas de risco; há oportunidade para pressionar imediatamente após passe para trás.');
  if(count('offside')>=3) insights.push('A linha defensiva procura subir; atacar a profundidade com movimentos temporizados.');
  if(state.events.length>=4){const busiest=observationZones.map(([id,name])=>({name,total:state.events.filter(e=>(e.zone||'center-mid')===id).length})).sort((a,b)=>b.total-a.total)[0];if(busiest.total)insights.push(`Zona com maior incidência: ${busiest.name}, com ${busiest.total} acontecimentos registados.`)}
  const first=state.events.filter(e=>(e.period||'1.ª parte')==='1.ª parte').length,second=state.events.filter(e=>e.period==='2.ª parte').length;if(first&&second&&Math.abs(first-second)>=3)insights.push(`A atividade registada foi superior na ${second>first?'segunda':'primeira'} parte (${Math.max(first,second)} contra ${Math.min(first,second)} acontecimentos).`);
  if(!insights.length) insights.push('A amostra ainda é reduzida. Continue o registo para obter conclusões automáticas mais específicas.');
  return insights;
}
function renderReport(){
  const max=Math.max(1,...eventTypes.map(e=>count(e.id))); const date=state.matchDate?new Intl.DateTimeFormat('pt-PT',{dateStyle:'long'}).format(new Date(state.matchDate+'T12:00:00')):new Intl.DateTimeFormat('pt-PT',{dateStyle:'long'}).format(new Date());
  const notes=noteTypes.map((n,i)=>({...n,index:i})).filter(n=>state.notes[n.index]);
  const subject=state.scope==='own'?'ANÁLISE DA MINHA EQUIPA':'OBSERVAÇÃO DO ADVERSÁRIO';
  const zoneCounts=Object.fromEntries(observationZones.map(([id])=>[id,state.events.filter(e=>(e.zone||'center-mid')===id).length]));
  const tactical=[state.blockHeight&&`Bloco ${state.blockHeight.toLowerCase()}`,state.pressingStyle&&`Pressão ${state.pressingStyle.toLowerCase()}`,state.buildUpStyle&&`Construção ${state.buildUpStyle.toLowerCase()}`,state.attackTempo&&`Ritmo ${state.attackTempo.toLowerCase()}`].filter(Boolean);
  const evidence=state.events.filter(e=>e.evidence);
  const discipline=state.events.filter(e=>cardEventIds.includes(e.id));
  const outcomes=['Positivo','Neutro','Negativo'].map(name=>({name,total:state.events.filter(e=>(e.outcome||'Neutro')===name).length})),outcomeTotal=Math.max(1,outcomes.reduce((sum,x)=>sum+x.total,0));
  const positivePct=Math.round(outcomes[0].total/outcomeTotal*100),neutralPct=Math.round(outcomes[1].total/outcomeTotal*100);
  const groupTotals=['Ofensivos','Defensivos','Transições','Controlo'].map(name=>({name,total:state.events.filter(e=>eventTypes.find(t=>t.id===e.id)?.group===name).length})),groupMax=Math.max(1,...groupTotals.map(x=>x.total));
  const moments=['Organização ofensiva','Organização defensiva','Transição ofensiva','Transição defensiva','Bola parada'].map(name=>({name,total:state.events.filter(e=>e.moment===name).length})),momentMax=Math.max(1,...moments.map(x=>x.total));
  $('#report').innerHTML=`<div class="report-hero"><span class="eyebrow">${subject}</span><h2>${state.team||'Equipa'}</h2><div class="report-meta">${date} · ${state.competition||'Competição não definida'}${state.matchRound?' · '+state.matchRound:''} · ${state.venue||'Local não definido'}${state.homeAway?' · '+state.homeAway:''}<br>${state.period} · ${formatTime(state.seconds)} observados · ${state.analyst||'Observador não identificado'}${state.finalScore?' · Resultado '+state.finalScore:''}</div></div>
  <div class="kpis"><div class="kpi"><strong>${count('attack')}</strong><span>ATAQUES</span></div><div class="kpi"><strong>${count('shot')}</strong><span>REMATES</span></div><div class="kpi"><strong>${state.score}</strong><span>GOLOS</span></div></div>
  <div class="report-block"><h3>Visão gráfica</h3><div class="report-charts"><div class="outcome-chart"><div class="donut" style="--positive:${positivePct};--neutral:${neutralPct}"><strong>${state.events.length}</strong><span>ações</span></div><div class="chart-legend">${outcomes.map((x,i)=>`<span class="legend-${i}"><i></i>${x.name}: <b>${x.total}</b></span>`).join('')}</div></div><div class="group-chart">${groupTotals.map(x=>`<div class="chart-row"><span>${x.name}</span><div><i style="width:${x.total/groupMax*100}%"></i></div><b>${x.total}</b></div>`).join('')}</div></div></div>
  <div class="report-block"><h3>Acontecimentos por momento do jogo</h3>${moments.map(x=>`<div class="bar-row"><div class="bar-label"><span>${x.name}</span><b>${x.total}</b></div><div class="bar"><i style="width:${x.total/momentMax*100}%"></i></div></div>`).join('')}</div>
  <div class="report-block"><h3>Contexto tático</h3><p><b>Objetivo da observação:</b> ${state.observationGoal||'Não definido.'}</p><p><b>Sistema observado:</b> ${state.scope==='own'?(state.formation||'Não definido'):(state.opponentFormation||'Não definido')}</p><p>${tactical.join(' · ')||'Perfil tático ainda não preenchido.'}</p>${state.systemChanges?`<p><b>Alterações de sistema:</b> ${state.systemChanges}</p>`:''}${state.substitutions?`<p><b>Substituições relevantes:</b> ${state.substitutions}</p>`:''}</div>
  <div class="report-block"><h3>Leitura automática</h3><ul>${generateInsights().map(x=>`<li>${x}</li>`).join('')}</ul></div>
  <div class="report-block"><h3>Indicadores do jogo</h3>${eventTypes.filter(e=>count(e.id)).map(e=>`<div class="bar-row"><div class="bar-label"><span>${e.icon} ${e.name}</span><b>${count(e.id)}</b></div><div class="bar"><i style="width:${count(e.id)/max*100}%"></i></div></div>`).join('')||'<p>Sem eventos registados.</p>'}</div>
  <div class="report-block"><h3>Mapa de acontecimentos</h3><div class="report-zone-grid">${observationZones.map(([id,name])=>`<div class="report-zone"><strong>${zoneCounts[id]}</strong><span>${name}</span></div>`).join('')}</div></div>
  ${notes.length?`<div class="report-block"><h3>Modelo de jogo</h3>${notes.map(n=>`<p><b>${n.group} — ${n.label}</b><br>${state.notes[n.index]}</p>`).join('')}</div>`:''}
  ${evidence.length?`<div class="report-block"><h3>Evidências selecionadas</h3><ul class="evidence-list">${evidence.map(e=>{const type=eventTypes.find(t=>t.id===e.id);return`<li><b>${formatTime(e.time)} — ${type?.name||e.id}</b>: ${observationZones.find(z=>z[0]===(e.zone||'center-mid'))?.[1]||''}${e.moment?' · '+e.moment:''}${e.outcome?' · '+e.outcome:''}${e.player?' · '+e.player:''}${e.note?' — '+e.note:''}</li>`}).join('')}</ul></div>`:''}
  ${discipline.length?`<div class="report-block"><h3>Registo disciplinar</h3><table class="discipline-table"><thead><tr><th>Minuto</th><th>Cartão</th><th>Jogador</th><th>Equipa</th><th>Motivo</th></tr></thead><tbody>${discipline.map(e=>`<tr><td>${formatTime(e.time)}</td><td>${eventTypes.find(t=>t.id===e.id)?.name||e.id}</td><td>${e.player||'Não identificado'}</td><td>${e.cardTeam==='opponent'?'Adversário':'Observada'}</td><td>${e.reason||'—'}</td></tr>`).join('')}</tbody></table></div>`:''}
  ${state.players.length?`<div class="report-block"><h3>Jogadores de referência</h3><ul>${state.players.map(p=>`<li><b>#${p.number||'—'} ${p.position||''} — ${p.name||'Sem nome'}</b> ${p.rating?`(${p.rating}/10)`:''}<br>${[p.role,p.positive,p.improve,(p.tags||[]).join(', ')].filter(Boolean).join(' · ')||'Sem observações.'}</li>`).join('')}</ul></div>`:''}
  <div class="report-block"><h3>Conclusões e plano de ação</h3><p><b>Pontos fortes:</b> ${state.strengths||'Não registados.'}</p><p><b>Pontos fracos:</b> ${state.weaknesses||state.vulnerabilities||'Não registados.'}</p><p><b>Como condicionar:</b> ${state.howToCondition||'Não definido.'}</p><p><b>Como explorar:</b> ${state.howToExploit||'Não definido.'}</p><p><b>Recomendações para o treino:</b> ${state.trainingRecommendations||'Não definidas.'}</p><p><b>Prioridade:</b> ${state.analysisPriority||'Não definida.'}</p></div>`;
}
function renderScope(){const own=state.scope==='own';$('#appTitle').textContent=own?'Análise da Minha Equipa':'Observação do Adversário';$$('[data-scope]').forEach(b=>b.classList.toggle('active',b.dataset.scope===state.scope));$('#vulnerabilities').previousElementSibling.textContent=own?'Aspetos a melhorar':'Vulnerabilidades a explorar';$('#vulnerabilities').placeholder=own?'Que aspetos deve a equipa melhorar?':'Onde e como pode a equipa ser explorada?'}
const observationFields=['competition','matchDate','venue','analyst','formation','opponentFormation','matchRound','homeAway','observationGoal','finalScore','systemChanges','substitutions'];
const quickFields=['eventMoment','eventOutcome','eventRelation','matchState','eventPlayer','eventQuickNote'];
const conclusionFields=['strengths','weaknesses','howToCondition','howToExploit','trainingRecommendations','analysisPriority'];
function sync(){ $('#team').value=state.team;$('#score').textContent=state.score;$('#clock').textContent=formatTime(state.seconds);$('#periodBtn').textContent=state.period;[...observationFields,...quickFields].forEach(id=>$('#'+id).value=state[id]||'');renderQuickContext();renderZones();renderEvents();renderNotes();renderScope() }
function toggleClock(){state.running=!state.running;$('#clockBtn').textContent=state.running?'❚❚ Pausar':'▶ Retomar jogo';$('.status').classList.toggle('live',state.running);$('#statusText').textContent=state.running?'EM DIRETO':'PAUSADO';clearInterval(timer);if(state.running)timer=setInterval(()=>{state.seconds++;$('#clock').textContent=formatTime(state.seconds);if(state.seconds%10===0)save()},1000);save()}
document.addEventListener('click',e=>{
  const event=e.target.dataset.event;if(event){if(cardEventIds.includes(event))openCardDialog(event);else recordEvent(event)}
  const zone=e.target.closest('[data-zone]')?.dataset.zone;if(zone){state.selectedZone=zone;renderZones();save()}
  const outcome=e.target.dataset.outcome;if(outcome){state.eventOutcome=outcome;$('#eventOutcome').value=outcome;renderQuickContext();save()}
  if(e.target.dataset.score){state.score=Math.max(0,state.score+Number(e.target.dataset.score));$('#score').textContent=state.score;save()}
  const tab=e.target.dataset.tab;if(tab){$$('.tabs button,.panel').forEach(x=>x.classList.remove('active'));e.target.classList.add('active');$('#'+tab).classList.add('active');if(tab==='relatorio'){renderReport();renderReportLibrary()}}
  const openReport=e.target.dataset.openReport;if(openReport)openSavedReport(openReport);
  const copyReport=e.target.dataset.copyReport;if(copyReport){const original=reports.find(r=>r.id===copyReport);if(original){const copy=JSON.parse(JSON.stringify(original));copy.id='report-'+Date.now();copy.title+=' (cópia)';copy.createdAt=copy.updatedAt=Date.now();reports.unshift(copy);persistReports();toast('Relatório duplicado')}}
  const deleteReport=e.target.dataset.deleteReport;if(deleteReport&&confirm('Eliminar este relatório guardado?')){reports=reports.filter(r=>r.id!==deleteReport);if(activeReportId===deleteReport)activeReportId=null;persistReports();toast('Relatório eliminado')}
  const scope=e.target.dataset.scope;if(scope){const wasDefault=state.team==='Adversário'||state.team==='Minha equipa';state.scope=scope;if(wasDefault)state.team=scope==='own'?'Minha equipa':'Adversário';sync();save()}
  if(e.target.dataset.removePlayer!==undefined){state.players.splice(Number(e.target.dataset.removePlayer),1);renderNotes();save()}
  if(e.target.dataset.evidence!==undefined){const i=Number(e.target.dataset.evidence);state.events[i].evidence=!state.events[i].evidence;renderEvents();save();toast(state.events[i].evidence?'Marcado como evidência':'Evidência removida')}
  if(e.target.dataset.playerTag!==undefined){const i=Number(e.target.dataset.playerTag),tag=e.target.dataset.tag,p=state.players[i];p.tags=p.tags||[];p.tags=p.tags.includes(tag)?p.tags.filter(x=>x!==tag):[...p.tags,tag];renderNotes();save()}
});
$('#clockBtn').onclick=toggleClock;
$('#periodBtn').onclick=()=>{state.period=state.period==='1.ª parte'?'2.ª parte':'1.ª parte';$('#periodBtn').textContent=state.period;save()};
function undoLastEvent(){const x=state.events.pop();if(x?.id==='goal')state.score=Math.max(0,state.score-1);sync();save();if(x)toast('Evento anulado')}
$('#undoBtn').onclick=undoLastEvent;$('#undoLastQuick').onclick=undoLastEvent;
$('#evidenceLastQuick').onclick=()=>{const last=state.events.at(-1);if(!last)return;last.evidence=!last.evidence;renderEvents();save();toast(last.evidence?'Marcado como evidência':'Evidência removida')};
$('#attackDirection').onclick=()=>{state.attackDirection=state.attackDirection==='right'?'left':'right';renderZones();save()};
$('#openReportQuick').onclick=()=>{const button=$('[data-tab="relatorio"]');button.click()};
$('#cardPlayer').onchange=updateCardWarning;
$('#cardTeam').onchange=()=>{if($('#cardTeam').value==='opponent'){$('#cardPlayer').value='';$('#cardPlayerManual').focus()}updateCardWarning()};
$('#confirmCard').onclick=()=>{const playerId=$('#cardPlayer').value,player=state.players.find(p=>p.id===playerId),manual=$('#cardPlayerManual').value.trim();let type=pendingCardType;const priorYellow=playerId&&state.events.some(e=>e.playerId===playerId&&e.id==='yellowCard');if(type==='yellowCard'&&priorYellow){if(!confirm('Este jogador já tem amarelo. Registar como segundo amarelo e expulsão?'))return;type='secondYellow'}const playerLabel=player?`${player.number?'#'+player.number+' ':''}${player.name||player.position||'Jogador'}`:manual||'Jogador não identificado';const reason=$('#cardReason').value,detail=$('#cardNote').value.trim();if(player&&type==='yellowCard'){player.tags=player.tags||[];if(!player.tags.includes('Risco disciplinar'))player.tags.push('Risco disciplinar')}recordEvent(type,{playerId:playerId||null,player:playerLabel,cardTeam:$('#cardTeam').value,reason,note:[reason,detail].filter(Boolean).join(' — ')});$('#cardDialog').close();pendingCardType=null};
$('#addPlayer').onclick=()=>{state.players.push({number:'',position:'',name:'',rating:'',foot:'',role:'',positive:'',improve:'',tags:[]});renderNotes();save()};
$('#resetBtn').onclick=()=>{if(confirm('Começar uma nova observação? Guarde primeiro o relatório atual se pretender consultá-lo mais tarde.')){clearInterval(timer);activeReportId=null;state=blank();sync();save()}};
document.addEventListener('input',e=>{if(e.target.id==='team')state.team=e.target.value;if([...observationFields,...quickFields,...conclusionFields].includes(e.target.id))state[e.target.id]=e.target.value;if(quickFields.includes(e.target.id))renderQuickContext();if(['blockHeight','pressingStyle','buildUpStyle','attackTempo'].includes(e.target.id))state[e.target.id]=e.target.value;if(e.target.dataset.note!==undefined)state.notes[e.target.dataset.note]=e.target.value;if(e.target.id==='vulnerabilities')state.vulnerabilities=e.target.value;if(e.target.dataset.playerNumber!==undefined)state.players[e.target.dataset.playerNumber].number=e.target.value;if(e.target.dataset.playerPosition!==undefined)state.players[e.target.dataset.playerPosition].position=e.target.value;if(e.target.dataset.playerName!==undefined)state.players[e.target.dataset.playerName].name=e.target.value;if(e.target.dataset.playerRating!==undefined)state.players[e.target.dataset.playerRating].rating=e.target.value;if(e.target.dataset.playerFoot!==undefined)state.players[e.target.dataset.playerFoot].foot=e.target.value;if(e.target.dataset.playerRole!==undefined)state.players[e.target.dataset.playerRole].role=e.target.value;if(e.target.dataset.playerPositive!==undefined)state.players[e.target.dataset.playerPositive].positive=e.target.value;if(e.target.dataset.playerImprove!==undefined)state.players[e.target.dataset.playerImprove].improve=e.target.value;save()});
$('#eventTypeFilter').innerHTML+=eventTypes.map(e=>`<option value="${e.id}">${e.name}</option>`).join('');
$('#eventTypeFilter').onchange=renderEvents;$('#eventPeriodFilter').onchange=renderEvents;
$('#printBtn').onclick=()=>window.print();
$('#saveReportBtn').onclick=saveCurrentReport;
$('#shareBtn').onclick=async()=>{renderReport();const text=`Relatório: ${state.team}\n${generateInsights().join('\n')}\nAtaques: ${count('attack')} · Remates: ${count('shot')} · Golos: ${state.score}\nPontos fortes: ${state.strengths||'—'}\nPontos fracos: ${state.weaknesses||state.vulnerabilities||'—'}\nComo explorar: ${state.howToExploit||'—'}\nTreino recomendado: ${state.trainingRecommendations||'—'}`;if(navigator.share){try{await navigator.share({title:`Observação — ${state.team}`,text})}catch{}}else{await navigator.clipboard.writeText(text);toast('Relatório copiado')}};
sync();renderReportLibrary(); if('serviceWorker' in navigator)navigator.serviceWorker.register('sw.js?v=7');

// Construtor de exercícios
const canvas=$('#tacticsCanvas'),ctx=canvas.getContext('2d');
const boardBlank=()=>({id:null,name:'',category:'',age:'',players:'',space:'',objective:'',duration:'',sets:'',rest:'',equipment:'',description:'',rules:'',variants:'',success:'',pitch:'full',items:[],frames:[]});
let board=boardBlank(),boardTool='select',boardHistory=[],dragIndex=-1,selectedIndex=-1,selectedFrameIndex=-1,drawStart=null,previewPoint=null,animationRunning=false;
let exercises=JSON.parse(localStorage.getItem('rf-football-exercises')||'[]');
const toolNames={select:'Selecione e arraste os elementos',home:'Toque no campo para adicionar Equipa A',away:'Toque no campo para adicionar Equipa B',neutral:'Toque no campo para adicionar um joker',ball:'Toque no campo para adicionar uma bola',cone:'Toque no campo para adicionar um cone',run:'Arraste para desenhar uma corrida',dribble:'Arraste para desenhar uma condução',pass:'Arraste para desenhar um passe',shot:'Arraste para indicar a direção do remate',corner:'Arraste para desenhar o canto',press:'Arraste para indicar a pressão',zone:'Arraste para marcar uma zona',delete:'Toque num elemento para apagar'};
function boardPoint(e){const r=canvas.getBoundingClientRect();return{x:(e.clientX-r.left)*canvas.width/r.width,y:(e.clientY-r.top)*canvas.height/r.height}}
function boardSnapshot(){boardHistory.push(JSON.stringify(board.items));if(boardHistory.length>30)boardHistory.shift()}
function drawPitch(){
  const w=canvas.width,h=canvas.height;ctx.clearRect(0,0,w,h);ctx.fillStyle='#347f4d';ctx.fillRect(0,0,w,h);
  for(let i=0;i<10;i++){ctx.fillStyle=i%2?'rgba(255,255,255,.025)':'rgba(0,0,0,.025)';ctx.fillRect(i*w/10,0,w/10,h)}
  if(board.pitch==='blank')return;ctx.strokeStyle='rgba(255,255,255,.9)';ctx.lineWidth=5;ctx.strokeRect(22,22,w-44,h-44);
  if(board.pitch==='full'){
    ctx.beginPath();ctx.moveTo(w/2,22);ctx.lineTo(w/2,h-22);ctx.stroke();ctx.beginPath();ctx.arc(w/2,h/2,92,0,Math.PI*2);ctx.stroke();
    [[22,1],[w-22,-1]].forEach(([x,d])=>{ctx.strokeRect(d>0?x:x-165,h/2-145,165,290);ctx.strokeRect(d>0?x:x-62,h/2-78,62,156);ctx.beginPath();ctx.arc(x+d*112,h/2,3,0,Math.PI*2);ctx.fillStyle='#fff';ctx.fill()});
  }else{
    ctx.beginPath();ctx.moveTo(22,h/2);ctx.lineTo(w-22,h/2);ctx.stroke();ctx.beginPath();ctx.arc(w/2,22,105,0,Math.PI);ctx.stroke();ctx.strokeRect(w/2-175,h-185,350,163);ctx.strokeRect(w/2-75,h-82,150,60);ctx.beginPath();ctx.arc(w/2,h-132,3,0,Math.PI*2);ctx.fillStyle='#fff';ctx.fill();
  }
}
function arrowHead(x1,y1,x2,y2,color,dashed,scale=1,curve=0){const dx=x2-x1,dy=y2-y1,len=Math.max(1,Math.hypot(dx,dy)),offset=curve*2.5,cx=(x1+x2)/2-dy/len*offset,cy=(y1+y2)/2+dx/len*offset,a=curve?Math.atan2(y2-cy,x2-cx):Math.atan2(dy,dx),size=18*scale;ctx.save();ctx.strokeStyle=color;ctx.fillStyle=color;ctx.lineWidth=8*scale;ctx.lineCap='round';ctx.setLineDash(dashed?[18*scale,13*scale]:[]);ctx.beginPath();ctx.moveTo(x1,y1);if(curve)ctx.quadraticCurveTo(cx,cy,x2,y2);else ctx.lineTo(x2,y2);ctx.stroke();ctx.setLineDash([]);ctx.beginPath();ctx.moveTo(x2,y2);ctx.lineTo(x2-size*Math.cos(a-.55),y2-size*Math.sin(a-.55));ctx.lineTo(x2-size*Math.cos(a+.55),y2-size*Math.sin(a+.55));ctx.closePath();ctx.fill();ctx.restore()}
function drawItem(o){
  const scale=o.scale||1;
  if(['run','dribble','pass','shot','corner','press'].includes(o.type)){const color={run:'#ffe458',dribble:'#53efff',pass:'#fff',shot:'#ff5964',corner:'#ffd447',press:'#d79cff'}[o.type];arrowHead(o.x,o.y,o.x2,o.y2,color,['run','dribble','press'].includes(o.type),scale,o.curve||0);return}
  if(o.type==='zone'){ctx.save();ctx.fillStyle='rgba(255,220,60,.18)';ctx.strokeStyle='#ffe458';ctx.lineWidth=5*scale;ctx.setLineDash([14*scale,10*scale]);ctx.fillRect(o.x,o.y,o.x2-o.x,o.y2-o.y);ctx.strokeRect(o.x,o.y,o.x2-o.x,o.y2-o.y);ctx.restore();return}
  ctx.save();ctx.translate(o.x,o.y);ctx.scale(scale,scale);
  if(['home','away','neutral'].includes(o.type)){const colors={home:'#1677ff',away:'#ef3340',neutral:'#f7d447'};ctx.beginPath();ctx.arc(0,0,25,0,Math.PI*2);ctx.fillStyle=o.color||colors[o.type];ctx.fill();ctx.strokeStyle=o.locked?'#ffd447':'#fff';ctx.lineWidth=5;ctx.stroke();ctx.fillStyle=o.type==='neutral'?'#2d321e':'#fff';ctx.font='bold 22px system-ui';ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText(o.label,0,1);if(o.name){ctx.font='bold 13px system-ui';const width=ctx.measureText(o.name).width+12;ctx.fillStyle='rgba(6,35,24,.82)';ctx.fillRect(-width/2,32,width,21);ctx.fillStyle='#fff';ctx.fillText(o.name,0,43)}}
  if(o.type==='ball'){ctx.beginPath();ctx.arc(0,0,16,0,Math.PI*2);ctx.fillStyle='#fff';ctx.fill();ctx.strokeStyle='#17241c';ctx.lineWidth=4;ctx.stroke();ctx.fillStyle='#17241c';ctx.font='19px serif';ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText('•',0,0)}
  if(o.type==='cone'){ctx.beginPath();ctx.moveTo(0,-22);ctx.lineTo(20,18);ctx.lineTo(-20,18);ctx.closePath();ctx.fillStyle='#ff8b22';ctx.fill();ctx.strokeStyle='#fff';ctx.lineWidth=3;ctx.stroke()}
  ctx.restore();
}
function renderBoard(){drawPitch();board.items.forEach(drawItem);if(selectedIndex>=0&&board.items[selectedIndex]&&!animationRunning){const o=board.items[selectedIndex],s=o.scale||1;ctx.save();ctx.strokeStyle='#fff';ctx.lineWidth=3;ctx.setLineDash([7,6]);if(['run','dribble','pass','shot','corner','press','zone'].includes(o.type)){const pad=12+Math.abs(o.curve||0)*2.5;ctx.strokeRect(Math.min(o.x,o.x2)-pad,Math.min(o.y,o.y2)-pad,Math.abs(o.x2-o.x)+pad*2,Math.abs(o.y2-o.y)+pad*2)}else{ctx.beginPath();ctx.arc(o.x,o.y,35*s,0,Math.PI*2);ctx.stroke()}ctx.restore()}if(drawStart&&previewPoint){drawItem({type:boardTool,x:drawStart.x,y:drawStart.y,x2:previewPoint.x,y2:previewPoint.y,scale:1,curve:0})}}
function itemHit(p){for(let i=board.items.length-1;i>=0;i--){const o=board.items[i],s=o.scale||1;if(['run','dribble','pass','shot','corner','press','zone'].includes(o.type)){const pad=20*s+Math.abs(o.curve||0)*2.5,minX=Math.min(o.x,o.x2)-pad,maxX=Math.max(o.x,o.x2)+pad,minY=Math.min(o.y,o.y2)-pad,maxY=Math.max(o.y,o.y2)+pad;if(p.x>=minX&&p.x<=maxX&&p.y>=minY&&p.y<=maxY)return i}else if(Math.hypot(p.x-o.x,p.y-o.y)<38*s)return i}return-1}
function nextLabel(type){return String(board.items.filter(x=>x.type===type).length+1)}
function newUid(){return Date.now().toString(36)+Math.random().toString(36).slice(2,7)}
function updateSizeControl(){const o=board.items[selectedIndex],range=$('#objectSize');range.disabled=!o;range.value=o?Math.round((o.scale||1)*100):100;$('#objectSizeValue').value=range.value+'%';updateTrajectoryControl();updateObjectProperties()}
function updateTrajectoryControl(){const o=board.items[selectedIndex],enabled=o&&['dribble','pass','shot','corner','press'].includes(o.type),range=$('#trajectoryCurve');range.disabled=!enabled;$('#straightTrajectory').disabled=!enabled;range.value=enabled?(o.curve||0):0;$('#trajectoryCurveValue').value=(Number(range.value)>0?'+':'')+range.value+'°'}
function updateObjectProperties(){const o=board.items[selectedIndex],isPlayer=o&&['home','away','neutral'].includes(o.type),panel=$('#playerProperties');panel.hidden=!isPlayer;if(!isPlayer)return;$('#playerNumber').value=o.label||'';$('#playerName').value=o.name||'';$('#playerColor').value=o.color||({home:'#1677ff',away:'#ef3340',neutral:'#f7d447'}[o.type]);$('#lockObject').textContent=o.locked?'🔒 Desbloquear':'🔓 Bloquear'}
canvas.addEventListener('pointerdown',e=>{e.preventDefault();const p=boardPoint(e),hit=itemHit(p);canvas.setPointerCapture(e.pointerId);
  if(animationRunning)return;
  if(boardTool==='select'){selectedIndex=hit;updateSizeControl();updateObjectProperties();renderBoard();if(hit>=0&&!board.items[hit].locked){boardSnapshot();dragIndex=hit}else if(hit>=0&&board.items[hit].locked)toast('Elemento bloqueado') ;return}
  if(boardTool==='delete'){if(hit>=0){boardSnapshot();board.items.splice(hit,1);selectedIndex=-1;updateSizeControl();updateObjectProperties();renderBoard()}return}
  if(['run','dribble','pass','shot','corner','press','zone'].includes(boardTool)){boardSnapshot();drawStart=p;previewPoint=p;return}
  if(['home','away','neutral','ball','cone'].includes(boardTool)){boardSnapshot();const colors={home:'#1677ff',away:'#ef3340',neutral:'#f7d447'};board.items.push({uid:newUid(),type:boardTool,x:p.x,y:p.y,label:nextLabel(boardTool),scale:1,color:colors[boardTool]});selectedIndex=board.items.length-1;updateSizeControl();updateObjectProperties();renderBoard()}
});
canvas.addEventListener('pointermove',e=>{const p=boardPoint(e);if(dragIndex>=0){const o=board.items[dragIndex],dx=p.x-o.x,dy=p.y-o.y;o.x=p.x;o.y=p.y;if(o.x2!==undefined){o.x2+=dx;o.y2+=dy}renderBoard()}else if(drawStart){previewPoint=p;renderBoard()}});
canvas.addEventListener('pointerup',()=>{if(drawStart&&previewPoint&&Math.hypot(previewPoint.x-drawStart.x,previewPoint.y-drawStart.y)>15){board.items.push({uid:newUid(),type:boardTool,x:drawStart.x,y:drawStart.y,x2:previewPoint.x,y2:previewPoint.y,scale:1,curve:0});selectedIndex=board.items.length-1;updateSizeControl();updateObjectProperties()}dragIndex=-1;drawStart=null;previewPoint=null;renderBoard()});
const boardFields={exerciseName:'name',exerciseCategory:'category',exerciseAge:'age',exercisePlayers:'players',exerciseSpace:'space',exerciseObjective:'objective',exerciseDuration:'duration',exerciseSets:'sets',exerciseRest:'rest',exerciseEquipment:'equipment',exerciseDescription:'description',exerciseRules:'rules',exerciseVariants:'variants',exerciseSuccess:'success'};
function syncBoardForm(){Object.entries(boardFields).forEach(([id,key])=>board[key]=$('#'+id).value);board.pitch=$('#pitchType').value}
function fillBoardForm(){board.items=board.items||[];board.frames=(board.frames||[]).map((f,i)=>Array.isArray(f)?{id:newUid(),name:`Etapa ${i+1}`,duration:900,items:f}:f);board.items.forEach(o=>{o.uid=o.uid||newUid();o.scale=o.scale||1;o.curve=o.curve||0});Object.entries(boardFields).forEach(([id,key])=>$('#'+id).value=board[key]||'');$('#pitchType').value=board.pitch;selectedIndex=-1;selectedFrameIndex=-1;updateSizeControl();renderTimeline();renderBoard() }
function escapeText(s){return String(s||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function renderExerciseList(){
  $('#exerciseCount').textContent=`${exercises.length} guardados`;const list=$('#exerciseList');list.className=exercises.length?'':'';
  list.innerHTML=exercises.length?exercises.map(x=>`<div class="exercise-row"><div><h3>${escapeText(x.name||'Exercício sem nome')}</h3><p>${escapeText(x.category||'Sem categoria')} · ${escapeText(x.objective||'Sem objetivo')} · ${escapeText(x.duration||'Duração não definida')}</p></div><div class="exercise-row-actions"><button data-load-exercise="${x.id}">Abrir</button><button class="delete-exercise" data-delete-exercise="${x.id}">×</button></div></div>`).join(''):'Ainda não existem exercícios guardados.';
}
function newBoard(){board=boardBlank();boardHistory=[];selectedIndex=-1;fillBoardForm();toast('Novo exercício')}
$$('[data-module]').forEach(b=>b.onclick=()=>{$$('[data-module]').forEach(x=>x.classList.toggle('active',x===b));$('#observationModule').classList.toggle('active',b.dataset.module==='observation');$('#builderModule').classList.toggle('active',b.dataset.module==='builder');$('#appTitle').textContent=b.dataset.module==='builder'?'Construtor de Exercícios':state.scope==='own'?'Análise da Minha Equipa':'Observação do Adversário';$('#resetBtn').style.visibility=b.dataset.module==='builder'?'hidden':'visible';if(b.dataset.module==='builder')renderBoard()});
$('#toolbox').onclick=e=>{const b=e.target.closest('[data-tool]');if(!b)return;boardTool=b.dataset.tool;$$('#toolbox button').forEach(x=>x.classList.toggle('active',x===b));$('#builderStatus').textContent=toolNames[boardTool]};
$('#pitchType').onchange=e=>{board.pitch=e.target.value;renderBoard()};
Object.keys(boardFields).forEach(id=>$('#'+id).addEventListener('input',syncBoardForm));
$('#undoBoard').onclick=()=>{if(boardHistory.length){board.items=JSON.parse(boardHistory.pop());selectedIndex=-1;updateSizeControl();renderBoard()}};
$('#clearBoard').onclick=()=>{if(board.items.length&&confirm('Limpar todos os elementos do campo?')){boardSnapshot();board.items=[];selectedIndex=-1;updateSizeControl();renderBoard()}};
$('#newExercise').onclick=()=>{if(!board.items.length&&!board.name)newBoard();else if(confirm('Criar um exercício novo?'))newBoard()};
$('#saveExercise').onclick=()=>{syncBoardForm();if(!board.name.trim()){toast('Indique o nome do exercício');$('#exerciseName').focus();return}if(!board.id)board.id=Date.now();const i=exercises.findIndex(x=>x.id===board.id),copy=JSON.parse(JSON.stringify(board));if(i>=0)exercises[i]=copy;else exercises.unshift(copy);const updatedAt=Date.now();localStorage.setItem('rf-football-exercises',JSON.stringify(exercises));localStorage.setItem('rf-football-exercises-updated',String(updatedAt));window.dispatchEvent(new CustomEvent('rf:exercises-changed',{detail:{data:exercises,updatedAt}}));renderExerciseList();toast('Exercício guardado')};
$('#exerciseList').onclick=e=>{const load=e.target.dataset.loadExercise,del=e.target.dataset.deleteExercise;if(load){const found=exercises.find(x=>x.id==load);if(found){board=JSON.parse(JSON.stringify(found));boardHistory=[];fillBoardForm();scrollTo({top:0,behavior:'smooth'});toast('Exercício aberto')}}if(del&&confirm('Apagar este exercício?')){exercises=exercises.filter(x=>x.id!=del);const updatedAt=Date.now();localStorage.setItem('rf-football-exercises',JSON.stringify(exercises));localStorage.setItem('rf-football-exercises-updated',String(updatedAt));window.dispatchEvent(new CustomEvent('rf:exercises-changed',{detail:{data:exercises,updatedAt}}));renderExerciseList()}};
$('#exportExercise').onclick=()=>{syncBoardForm();const out=document.createElement('canvas');out.width=1050;out.height=980;const c=out.getContext('2d');c.fillStyle='#fff';c.fillRect(0,0,out.width,out.height);c.fillStyle='#0b3f2e';c.font='bold 36px system-ui';c.fillText(board.name||'Exercício RF Football',28,48);c.fillStyle='#65736c';c.font='18px system-ui';c.fillText([board.category,board.age,board.players&&`${board.players} jogadores`,board.duration].filter(Boolean).join(' · '),28,82);c.fillStyle='#0b3f2e';c.font='bold 18px system-ui';c.fillText(board.objective||'Objetivo não definido',28,116);c.fillStyle='#65736c';c.font='16px system-ui';c.fillText([board.space&&`Espaço: ${board.space}`,board.sets,board.rest&&`Rec.: ${board.rest}`].filter(Boolean).join(' · '),28,145);c.drawImage(canvas,0,170,1050,680);c.fillStyle='#0b3f2e';c.font='bold 16px system-ui';c.fillText('Organização',28,885);c.fillStyle='#65736c';c.font='15px system-ui';c.fillText((board.description||'Sem descrição').slice(0,125),28,912);c.fillStyle='#0b3f2e';c.font='bold 16px system-ui';c.fillText('Material',28,944);c.fillStyle='#65736c';c.font='15px system-ui';c.fillText((board.equipment||'Não definido').slice(0,125),115,944);const a=document.createElement('a');a.download=(board.name||'exercicio-rf-football').replace(/[^a-z0-9áàâãéêíóôõúç_-]+/gi,'-')+'.png';a.href=out.toDataURL('image/png');a.click();toast('Ficha exportada')};
$('#objectSize').addEventListener('pointerdown',()=>{if(selectedIndex>=0)boardSnapshot()});
$('#objectSize').addEventListener('input',e=>{const o=board.items[selectedIndex];if(!o)return;o.scale=Number(e.target.value)/100;$('#objectSizeValue').value=e.target.value+'%';renderBoard()});
$('#trajectoryCurve').addEventListener('pointerdown',()=>{if(selectedIndex>=0)boardSnapshot()});
$('#trajectoryCurve').addEventListener('input',e=>{const o=board.items[selectedIndex];if(!o)return;o.curve=Number(e.target.value);$('#trajectoryCurveValue').value=(o.curve>0?'+':'')+o.curve+'°';renderBoard()});
$('#straightTrajectory').onclick=()=>{const o=board.items[selectedIndex];if(!o)return;boardSnapshot();o.curve=0;updateTrajectoryControl();renderBoard()};
['playerNumber','playerName','playerColor'].forEach(id=>$('#'+id).addEventListener('input',()=>{const o=board.items[selectedIndex];if(!o)return;if(id==='playerNumber')o.label=$('#'+id).value;if(id==='playerName')o.name=$('#'+id).value;if(id==='playerColor')o.color=$('#'+id).value;renderBoard()}));
$('#duplicateObject').onclick=()=>{const o=board.items[selectedIndex];if(!o)return;boardSnapshot();const copy={...o,uid:newUid(),x:o.x+45,y:o.y+45};if(copy.x2!==undefined){copy.x2+=45;copy.y2+=45}board.items.push(copy);selectedIndex=board.items.length-1;updateSizeControl();renderBoard();toast('Elemento duplicado')};
$('#lockObject').onclick=()=>{const o=board.items[selectedIndex];if(!o)return;o.locked=!o.locked;updateObjectProperties();renderBoard()};
function updateFrameCount(){const n=(board.frames||[]).length;$('#frameCount').textContent=`${n} ${n===1?'etapa':'etapas'}`;$('#updateFrame').disabled=selectedFrameIndex<0}
function renderTimeline(){updateFrameCount();const timeline=$('#timeline');timeline.innerHTML=board.frames.length?board.frames.map((f,i)=>`<article class="frame-card ${i===selectedFrameIndex?'active':''}" data-frame-card="${i}"><div class="frame-card-top"><input data-frame-name="${i}" value="${escapeText(f.name||`Etapa ${i+1}`)}" aria-label="Nome da etapa"></div><small>${f.items.length} elementos · ${Math.round((f.duration||900)/100)/10}s</small><div class="frame-actions"><button title="Ver etapa" data-frame-view="${i}">◉</button><button title="Mover para trás" data-frame-left="${i}">←</button><button title="Mover para a frente" data-frame-right="${i}">→</button><button title="Duplicar" data-frame-copy="${i}">⧉</button><button class="danger" title="Eliminar" data-frame-delete="${i}">×</button></div></article>`).join(''):'<div class="empty">Guarde a primeira etapa para criar a animação.</div>'}
$('#addFrame').onclick=()=>{if(!board.items.length){toast('Adicione jogadores ao campo primeiro');return}board.frames=board.frames||[];board.frames.push({id:newUid(),name:`Etapa ${board.frames.length+1}`,duration:Number($('#animationSpeed').value),items:JSON.parse(JSON.stringify(board.items))});selectedFrameIndex=board.frames.length-1;renderTimeline();toast(`Etapa ${board.frames.length} guardada`)};
$('#updateFrame').onclick=()=>{if(selectedFrameIndex<0)return;board.frames[selectedFrameIndex].items=JSON.parse(JSON.stringify(board.items));board.frames[selectedFrameIndex].duration=Number($('#animationSpeed').value);renderTimeline();toast('Etapa atualizada')};
$('#timeline').addEventListener('input',e=>{if(e.target.dataset.frameName!==undefined){board.frames[Number(e.target.dataset.frameName)].name=e.target.value}});
$('#timeline').addEventListener('click',e=>{const get=k=>e.target.dataset[k]!==undefined?Number(e.target.dataset[k]):-1;let i=get('frameView');if(i>=0){selectedFrameIndex=i;board.items=JSON.parse(JSON.stringify(board.frames[i].items));selectedIndex=-1;updateSizeControl();renderTimeline();renderBoard();return}i=get('frameLeft');if(i>0){[board.frames[i-1],board.frames[i]]=[board.frames[i],board.frames[i-1]];selectedFrameIndex=i-1;renderTimeline();return}i=get('frameRight');if(i>=0&&i<board.frames.length-1){[board.frames[i+1],board.frames[i]]=[board.frames[i],board.frames[i+1]];selectedFrameIndex=i+1;renderTimeline();return}i=get('frameCopy');if(i>=0){const copy=JSON.parse(JSON.stringify(board.frames[i]));copy.id=newUid();copy.name+=' (cópia)';board.frames.splice(i+1,0,copy);selectedFrameIndex=i+1;renderTimeline();return}i=get('frameDelete');if(i>=0&&confirm('Eliminar esta etapa?')){board.frames.splice(i,1);selectedFrameIndex=-1;renderTimeline()}});
function interpolateItems(from,to,t){
  const byId=new Map(to.map(o=>[o.uid,o]));const ease=t<.5?2*t*t:1-Math.pow(-2*t+2,2)/2;
  const result=from.map(a=>{const b=byId.get(a.uid)||a,c={...a};['x','y','x2','y2','scale','curve'].forEach(k=>{if(Number.isFinite(a[k])&&Number.isFinite(b[k]))c[k]=a[k]+(b[k]-a[k])*ease});return c});
  to.forEach(b=>{if(!result.some(a=>a.uid===b.uid)&&t>.45)result.push({...b})});return result;
}
function animateLeg(from,to,duration){return new Promise(resolve=>{const started=performance.now();function tick(now){const t=Math.min(1,(now-started)/duration);board.items=interpolateItems(from,to,t);renderBoard();if(t<1)requestAnimationFrame(tick);else resolve()}requestAnimationFrame(tick)})}
$('#playAnimation').onclick=async()=>{if(animationRunning)return;board.frames=board.frames||[];if(board.frames.length<2){toast('Guarde pelo menos duas etapas');return}animationRunning=true;selectedIndex=-1;selectedFrameIndex=-1;updateSizeControl();renderTimeline();$('#playAnimation').textContent='❚❚ A animar…';for(let i=0;i<board.frames.length-1;i++)await animateLeg(board.frames[i].items,board.frames[i+1].items,board.frames[i+1].duration||Number($('#animationSpeed').value));board.items=JSON.parse(JSON.stringify(board.frames.at(-1).items));animationRunning=false;$('#playAnimation').textContent='▶ Animar';renderBoard();toast('Animação concluída')};
fillBoardForm();renderExerciseList();
